/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AppointmentStatus = IDL.Variant({
  'Confirmed' : IDL.Null,
  'Cancelled' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const CallType = IDL.Variant({
  'VideoCall' : IDL.Null,
  'NormalCall' : IDL.Null,
});
export const Appointment = IDL.Record({
  'id' : IDL.Nat,
  'status' : AppointmentStatus,
  'doctorId' : IDL.Nat,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'slot' : IDL.Text,
  'callType' : CallType,
  'confirmationNumber' : IDL.Text,
});
export const BookingStatus = IDL.Variant({
  'Booked' : IDL.Null,
  'Cancelled' : IDL.Null,
});
export const ExerciseBooking = IDL.Record({
  'id' : IDL.Nat,
  'status' : BookingStatus,
  'userId' : UserId,
  'bookingDate' : Timestamp,
  'sessionId' : IDL.Nat,
  'timeSlot' : IDL.Text,
});
export const DietLogEntry = IDL.Record({
  'id' : IDL.Nat,
  'userId' : UserId,
  'calories' : IDL.Nat,
  'grams' : IDL.Float64,
  'timestamp' : Timestamp,
  'quantity' : IDL.Text,
  'foodName' : IDL.Text,
});
export const OrderItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Nat,
});
export const OrderNumber = IDL.Text;
export const ShoppingOrder = IDL.Record({
  'id' : IDL.Nat,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'totalAmount' : IDL.Nat,
  'items' : IDL.Vec(OrderItem),
  'orderNumber' : OrderNumber,
});
export const KitStatus = IDL.Variant({
  'Received' : IDL.Null,
  'Pending' : IDL.Null,
});
export const PlanType = IDL.Variant({
  'OneYear' : IDL.Null,
  'SixMonth' : IDL.Null,
  'ThreeMonth' : IDL.Null,
});
export const Subscription = IDL.Record({
  'id' : IDL.Nat,
  'purchaseDate' : Timestamp,
  'userId' : UserId,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'kitStatus' : KitStatus,
  'phone' : IDL.Text,
  'orderNumber' : OrderNumber,
  'amount' : IDL.Nat,
  'planType' : PlanType,
});
export const Doctor = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'specialty' : IDL.Text,
  'availableSlots' : IDL.Vec(IDL.Text),
  'phone' : IDL.Text,
});
export const MessageRole = IDL.Variant({
  'User' : IDL.Null,
  'Assistant' : IDL.Null,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'userId' : UserId,
  'role' : MessageRole,
  'timestamp' : Timestamp,
});
export const ProductCategory = IDL.Variant({
  'DiabetesFood' : IDL.Null,
  'Medicine' : IDL.Null,
  'ExerciseEquipment' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'category' : ProductCategory,
  'price' : IDL.Nat,
});
export const ExerciseSession = IDL.Record({
  'id' : IDL.Nat,
  'duration' : IDL.Nat,
  'instructor' : IDL.Text,
  'dayOfWeek' : IDL.Text,
  'name' : IDL.Text,
  'youtubeThumbnail' : IDL.Text,
  'description' : IDL.Text,
  'youtubeUrl' : IDL.Text,
  'timeSlot' : IDL.Text,
});

export const idlService = IDL.Service({
  'adminGetAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'adminGetAllBookings' : IDL.Func([], [IDL.Vec(ExerciseBooking)], ['query']),
  'adminGetAllDietLogs' : IDL.Func([], [IDL.Vec(DietLogEntry)], ['query']),
  'adminGetAllOrders' : IDL.Func([], [IDL.Vec(ShoppingOrder)], ['query']),
  'adminGetAllSubscriptions' : IDL.Func([], [IDL.Vec(Subscription)], ['query']),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'bookAppointment' : IDL.Func(
      [IDL.Nat, IDL.Text, CallType],
      [Appointment],
      [],
    ),
  'bookSession' : IDL.Func([IDL.Nat], [ExerciseBooking], []),
  'cancelAppointment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'cancelBooking' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteDietLog' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllUsers' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'name' : IDL.Text,
            'createdAt' : IDL.Int,
            'email' : IDL.Text,
          })
        ),
      ],
      [],
    ),
  'getCallerPrincipal' : IDL.Func([], [IDL.Principal], ['query']),
  'getDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
  'getMyAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getMyBookings' : IDL.Func([], [IDL.Vec(ExerciseBooking)], ['query']),
  'getMyChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getMyDietLogs' : IDL.Func([], [IDL.Vec(DietLogEntry)], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(ShoppingOrder)], ['query']),
  'getMySubscriptions' : IDL.Func([], [IDL.Vec(Subscription)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getSessions' : IDL.Func([], [IDL.Vec(ExerciseSession)], ['query']),
  'getUserCount' : IDL.Func([], [IDL.Nat], ['query']),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logFoodItem' : IDL.Func([IDL.Text, IDL.Text], [DietLogEntry], []),
  'loginUser' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'markKitReceived' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'placeOrder' : IDL.Func([IDL.Vec(OrderItem)], [ShoppingOrder], []),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'sendChatMessage' : IDL.Func([IDL.Text], [IDL.Text], []),
  'subscribePlan' : IDL.Func(
      [PlanType, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Subscription],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AppointmentStatus = IDL.Variant({
    'Confirmed' : IDL.Null,
    'Cancelled' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const CallType = IDL.Variant({
    'VideoCall' : IDL.Null,
    'NormalCall' : IDL.Null,
  });
  const Appointment = IDL.Record({
    'id' : IDL.Nat,
    'status' : AppointmentStatus,
    'doctorId' : IDL.Nat,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'slot' : IDL.Text,
    'callType' : CallType,
    'confirmationNumber' : IDL.Text,
  });
  const BookingStatus = IDL.Variant({
    'Booked' : IDL.Null,
    'Cancelled' : IDL.Null,
  });
  const ExerciseBooking = IDL.Record({
    'id' : IDL.Nat,
    'status' : BookingStatus,
    'userId' : UserId,
    'bookingDate' : Timestamp,
    'sessionId' : IDL.Nat,
    'timeSlot' : IDL.Text,
  });
  const DietLogEntry = IDL.Record({
    'id' : IDL.Nat,
    'userId' : UserId,
    'calories' : IDL.Nat,
    'grams' : IDL.Float64,
    'timestamp' : Timestamp,
    'quantity' : IDL.Text,
    'foodName' : IDL.Text,
  });
  const OrderItem = IDL.Record({
    'productId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Nat,
  });
  const OrderNumber = IDL.Text;
  const ShoppingOrder = IDL.Record({
    'id' : IDL.Nat,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'totalAmount' : IDL.Nat,
    'items' : IDL.Vec(OrderItem),
    'orderNumber' : OrderNumber,
  });
  const KitStatus = IDL.Variant({
    'Received' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const PlanType = IDL.Variant({
    'OneYear' : IDL.Null,
    'SixMonth' : IDL.Null,
    'ThreeMonth' : IDL.Null,
  });
  const Subscription = IDL.Record({
    'id' : IDL.Nat,
    'purchaseDate' : Timestamp,
    'userId' : UserId,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'kitStatus' : KitStatus,
    'phone' : IDL.Text,
    'orderNumber' : OrderNumber,
    'amount' : IDL.Nat,
    'planType' : PlanType,
  });
  const Doctor = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'specialty' : IDL.Text,
    'availableSlots' : IDL.Vec(IDL.Text),
    'phone' : IDL.Text,
  });
  const MessageRole = IDL.Variant({
    'User' : IDL.Null,
    'Assistant' : IDL.Null,
  });
  const ChatMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'userId' : UserId,
    'role' : MessageRole,
    'timestamp' : Timestamp,
  });
  const ProductCategory = IDL.Variant({
    'DiabetesFood' : IDL.Null,
    'Medicine' : IDL.Null,
    'ExerciseEquipment' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'category' : ProductCategory,
    'price' : IDL.Nat,
  });
  const ExerciseSession = IDL.Record({
    'id' : IDL.Nat,
    'duration' : IDL.Nat,
    'instructor' : IDL.Text,
    'dayOfWeek' : IDL.Text,
    'name' : IDL.Text,
    'youtubeThumbnail' : IDL.Text,
    'description' : IDL.Text,
    'youtubeUrl' : IDL.Text,
    'timeSlot' : IDL.Text,
  });
  
  return IDL.Service({
    'adminGetAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'adminGetAllBookings' : IDL.Func([], [IDL.Vec(ExerciseBooking)], ['query']),
    'adminGetAllDietLogs' : IDL.Func([], [IDL.Vec(DietLogEntry)], ['query']),
    'adminGetAllOrders' : IDL.Func([], [IDL.Vec(ShoppingOrder)], ['query']),
    'adminGetAllSubscriptions' : IDL.Func(
        [],
        [IDL.Vec(Subscription)],
        ['query'],
      ),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'bookAppointment' : IDL.Func(
        [IDL.Nat, IDL.Text, CallType],
        [Appointment],
        [],
      ),
    'bookSession' : IDL.Func([IDL.Nat], [ExerciseBooking], []),
    'cancelAppointment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'cancelBooking' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteDietLog' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllUsers' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'name' : IDL.Text,
              'createdAt' : IDL.Int,
              'email' : IDL.Text,
            })
          ),
        ],
        [],
      ),
    'getCallerPrincipal' : IDL.Func([], [IDL.Principal], ['query']),
    'getDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
    'getMyAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getMyBookings' : IDL.Func([], [IDL.Vec(ExerciseBooking)], ['query']),
    'getMyChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getMyDietLogs' : IDL.Func([], [IDL.Vec(DietLogEntry)], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(ShoppingOrder)], ['query']),
    'getMySubscriptions' : IDL.Func([], [IDL.Vec(Subscription)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getSessions' : IDL.Func([], [IDL.Vec(ExerciseSession)], ['query']),
    'getUserCount' : IDL.Func([], [IDL.Nat], ['query']),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logFoodItem' : IDL.Func([IDL.Text, IDL.Text], [DietLogEntry], []),
    'loginUser' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'markKitReceived' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'placeOrder' : IDL.Func([IDL.Vec(OrderItem)], [ShoppingOrder], []),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'sendChatMessage' : IDL.Func([IDL.Text], [IDL.Text], []),
    'subscribePlan' : IDL.Func(
        [PlanType, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Subscription],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };