/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : bigint,
  'status' : AppointmentStatus,
  'doctorId' : bigint,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'slot' : string,
  'callType' : CallType,
  'confirmationNumber' : string,
}
export type AppointmentStatus = { 'Confirmed' : null } |
  { 'Cancelled' : null };
export type BookingStatus = { 'Booked' : null } |
  { 'Cancelled' : null };
export type CallType = { 'VideoCall' : null } |
  { 'NormalCall' : null };
export interface ChatMessage {
  'id' : bigint,
  'content' : string,
  'userId' : UserId,
  'role' : MessageRole,
  'timestamp' : Timestamp,
}
export interface DietLogEntry {
  'id' : bigint,
  'userId' : UserId,
  'calories' : bigint,
  'grams' : number,
  'timestamp' : Timestamp,
  'quantity' : string,
  'foodName' : string,
}
export interface Doctor {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'specialty' : string,
  'availableSlots' : Array<string>,
  'phone' : string,
}
export interface ExerciseBooking {
  'id' : bigint,
  'status' : BookingStatus,
  'userId' : UserId,
  'bookingDate' : Timestamp,
  'sessionId' : bigint,
  'timeSlot' : string,
}
export interface ExerciseSession {
  'id' : bigint,
  'duration' : bigint,
  'instructor' : string,
  'dayOfWeek' : string,
  'name' : string,
  'youtubeThumbnail' : string,
  'description' : string,
  'youtubeUrl' : string,
  'timeSlot' : string,
}
export type KitStatus = { 'Received' : null } |
  { 'Pending' : null };
export type MessageRole = { 'User' : null } |
  { 'Assistant' : null };
export interface OrderItem {
  'productId' : bigint,
  'quantity' : bigint,
  'unitPrice' : bigint,
}
export type OrderNumber = string;
export type PlanType = { 'OneYear' : null } |
  { 'SixMonth' : null } |
  { 'ThreeMonth' : null };
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'imageUrl' : [] | [string],
  'category' : ProductCategory,
  'price' : bigint,
}
export type ProductCategory = { 'DiabetesFood' : null } |
  { 'Medicine' : null } |
  { 'ExerciseEquipment' : null };
export interface ShoppingOrder {
  'id' : bigint,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'totalAmount' : bigint,
  'items' : Array<OrderItem>,
  'orderNumber' : OrderNumber,
}
export interface Subscription {
  'id' : bigint,
  'purchaseDate' : Timestamp,
  'userId' : UserId,
  'name' : string,
  'email' : string,
  'address' : string,
  'kitStatus' : KitStatus,
  'phone' : string,
  'orderNumber' : OrderNumber,
  'amount' : bigint,
  'planType' : PlanType,
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface _SERVICE {
  'adminGetAllAppointments' : ActorMethod<[], Array<Appointment>>,
  'adminGetAllBookings' : ActorMethod<[], Array<ExerciseBooking>>,
  'adminGetAllDietLogs' : ActorMethod<[], Array<DietLogEntry>>,
  'adminGetAllOrders' : ActorMethod<[], Array<ShoppingOrder>>,
  'adminGetAllSubscriptions' : ActorMethod<[], Array<Subscription>>,
  'adminLogin' : ActorMethod<[string, string], boolean>,
  'bookAppointment' : ActorMethod<[bigint, string, CallType], Appointment>,
  'bookSession' : ActorMethod<[bigint], ExerciseBooking>,
  'cancelAppointment' : ActorMethod<[bigint], boolean>,
  'cancelBooking' : ActorMethod<[bigint], boolean>,
  'deleteDietLog' : ActorMethod<[bigint], boolean>,
  'getAllUsers' : ActorMethod<
    [],
    Array<{ 'name' : string, 'createdAt' : bigint, 'email' : string }>
  >,
  'getCallerPrincipal' : ActorMethod<[], Principal>,
  'getDoctors' : ActorMethod<[], Array<Doctor>>,
  'getMyAppointments' : ActorMethod<[], Array<Appointment>>,
  'getMyBookings' : ActorMethod<[], Array<ExerciseBooking>>,
  'getMyChatHistory' : ActorMethod<[], Array<ChatMessage>>,
  'getMyDietLogs' : ActorMethod<[], Array<DietLogEntry>>,
  'getMyOrders' : ActorMethod<[], Array<ShoppingOrder>>,
  'getMySubscriptions' : ActorMethod<[], Array<Subscription>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getSessions' : ActorMethod<[], Array<ExerciseSession>>,
  'getUserCount' : ActorMethod<[], bigint>,
  'isAdmin' : ActorMethod<[], boolean>,
  'logFoodItem' : ActorMethod<[string, string], DietLogEntry>,
  'loginUser' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'markKitReceived' : ActorMethod<[bigint], boolean>,
  'placeOrder' : ActorMethod<[Array<OrderItem>], ShoppingOrder>,
  'registerUser' : ActorMethod<
    [string, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'sendChatMessage' : ActorMethod<[string], string>,
  'subscribePlan' : ActorMethod<
    [PlanType, string, string, string, string],
    Subscription
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];