/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface ExerciseSession {
    id: bigint;
    duration: bigint;
    instructor: string;
    dayOfWeek: string;
    name: string;
    youtubeThumbnail: string;
    description: string;
    youtubeUrl: string;
    timeSlot: string;
}
export interface OrderItem {
    productId: bigint;
    quantity: bigint;
    unitPrice: bigint;
}
export interface Subscription {
    id: bigint;
    purchaseDate: Timestamp;
    userId: UserId;
    name: string;
    email: string;
    address: string;
    kitStatus: KitStatus;
    phone: string;
    orderNumber: OrderNumber;
    amount: bigint;
    planType: PlanType;
}
export type UserId = Principal;
export interface ExerciseBooking {
    id: bigint;
    status: BookingStatus;
    userId: UserId;
    bookingDate: Timestamp;
    sessionId: bigint;
    timeSlot: string;
}
export interface DietLogEntry {
    id: bigint;
    userId: UserId;
    calories: bigint;
    grams: number;
    timestamp: Timestamp;
    quantity: string;
    foodName: string;
}
export interface Doctor {
    id: bigint;
    name: string;
    email: string;
    specialty: string;
    availableSlots: Array<string>;
    phone: string;
}
export type OrderNumber = string;
export interface ChatMessage {
    id: bigint;
    content: string;
    userId: UserId;
    role: MessageRole;
    timestamp: Timestamp;
}
export interface ShoppingOrder {
    id: bigint;
    userId: UserId;
    createdAt: Timestamp;
    totalAmount: bigint;
    items: Array<OrderItem>;
    orderNumber: OrderNumber;
}
export interface Product {
    id: bigint;
    name: string;
    description: string;
    imageUrl?: string;
    category: ProductCategory;
    price: bigint;
}
export interface Appointment {
    id: bigint;
    status: AppointmentStatus;
    doctorId: bigint;
    userId: UserId;
    createdAt: Timestamp;
    slot: string;
    callType: CallType;
    confirmationNumber: string;
}
export enum AppointmentStatus {
    Confirmed = "Confirmed",
    Cancelled = "Cancelled"
}
export enum BookingStatus {
    Booked = "Booked",
    Cancelled = "Cancelled"
}
export enum CallType {
    VideoCall = "VideoCall",
    NormalCall = "NormalCall"
}
export enum KitStatus {
    Received = "Received",
    Pending = "Pending"
}
export enum MessageRole {
    User = "User",
    Assistant = "Assistant"
}
export enum PlanType {
    OneYear = "OneYear",
    SixMonth = "SixMonth",
    ThreeMonth = "ThreeMonth"
}
export enum ProductCategory {
    DiabetesFood = "DiabetesFood",
    Medicine = "Medicine",
    ExerciseEquipment = "ExerciseEquipment"
}
export interface backendInterface {
    adminGetAllAppointments(): Promise<Array<Appointment>>;
    adminGetAllBookings(): Promise<Array<ExerciseBooking>>;
    adminGetAllDietLogs(): Promise<Array<DietLogEntry>>;
    adminGetAllOrders(): Promise<Array<ShoppingOrder>>;
    adminGetAllSubscriptions(): Promise<Array<Subscription>>;
    adminLogin(email: string, password: string): Promise<boolean>;
    bookAppointment(doctorId: bigint, slot: string, callType: CallType): Promise<Appointment>;
    bookSession(sessionId: bigint): Promise<ExerciseBooking>;
    cancelAppointment(appointmentId: bigint): Promise<boolean>;
    cancelBooking(bookingId: bigint): Promise<boolean>;
    deleteDietLog(entryId: bigint): Promise<boolean>;
    getAllUsers(): Promise<Array<{
        name: string;
        createdAt: bigint;
        email: string;
    }>>;
    getCallerPrincipal(): Promise<Principal>;
    getDoctors(): Promise<Array<Doctor>>;
    getMyAppointments(): Promise<Array<Appointment>>;
    getMyBookings(): Promise<Array<ExerciseBooking>>;
    getMyChatHistory(): Promise<Array<ChatMessage>>;
    getMyDietLogs(): Promise<Array<DietLogEntry>>;
    getMyOrders(): Promise<Array<ShoppingOrder>>;
    getMySubscriptions(): Promise<Array<Subscription>>;
    getProducts(): Promise<Array<Product>>;
    getSessions(): Promise<Array<ExerciseSession>>;
    getUserCount(): Promise<bigint>;
    isAdmin(): Promise<boolean>;
    logFoodItem(foodName: string, quantity: string): Promise<DietLogEntry>;
    loginUser(email: string, password: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    markKitReceived(subscriptionId: bigint): Promise<boolean>;
    placeOrder(items: Array<OrderItem>): Promise<ShoppingOrder>;
    registerUser(name: string, email: string, password: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    sendChatMessage(userMessage: string): Promise<string>;
    subscribePlan(planType: PlanType, name: string, phone: string, email: string, address: string): Promise<Subscription>;
}
import type { Appointment as _Appointment, AppointmentStatus as _AppointmentStatus, BookingStatus as _BookingStatus, CallType as _CallType, ChatMessage as _ChatMessage, ExerciseBooking as _ExerciseBooking, KitStatus as _KitStatus, MessageRole as _MessageRole, OrderNumber as _OrderNumber, PlanType as _PlanType, Product as _Product, ProductCategory as _ProductCategory, Subscription as _Subscription, Timestamp as _Timestamp, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async adminGetAllAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllAppointments();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllAppointments();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetAllBookings(): Promise<Array<ExerciseBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllBookings();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllBookings();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetAllDietLogs(): Promise<Array<DietLogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllDietLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllDietLogs();
            return result;
        }
    }
    async adminGetAllOrders(): Promise<Array<ShoppingOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllOrders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllOrders();
            return result;
        }
    }
    async adminGetAllSubscriptions(): Promise<Array<Subscription>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllSubscriptions();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllSubscriptions();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminLogin(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0, arg1);
            return result;
        }
    }
    async bookAppointment(arg0: bigint, arg1: string, arg2: CallType): Promise<Appointment> {
        if (this.processError) {
            try {
                const result = await this.actor.bookAppointment(arg0, arg1, to_candid_CallType_n20(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Appointment_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookAppointment(arg0, arg1, to_candid_CallType_n20(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Appointment_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async bookSession(arg0: bigint): Promise<ExerciseBooking> {
        if (this.processError) {
            try {
                const result = await this.actor.bookSession(arg0);
                return from_candid_ExerciseBooking_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookSession(arg0);
            return from_candid_ExerciseBooking_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async cancelAppointment(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelAppointment(arg0);
            return result;
        }
    }
    async cancelBooking(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelBooking(arg0);
            return result;
        }
    }
    async deleteDietLog(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDietLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDietLog(arg0);
            return result;
        }
    }
    async getAllUsers(): Promise<Array<{
        name: string;
        createdAt: bigint;
        email: string;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return result;
        }
    }
    async getCallerPrincipal(): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerPrincipal();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerPrincipal();
            return result;
        }
    }
    async getDoctors(): Promise<Array<Doctor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoctors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoctors();
            return result;
        }
    }
    async getMyAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyAppointments();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyAppointments();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyBookings(): Promise<Array<ExerciseBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBookings();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBookings();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyChatHistory(): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyChatHistory();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyChatHistory();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyDietLogs(): Promise<Array<DietLogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyDietLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyDietLogs();
            return result;
        }
    }
    async getMyOrders(): Promise<Array<ShoppingOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyOrders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyOrders();
            return result;
        }
    }
    async getMySubscriptions(): Promise<Array<Subscription>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySubscriptions();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySubscriptions();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSessions(): Promise<Array<ExerciseSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessions();
            return result;
        }
    }
    async getUserCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserCount();
            return result;
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async logFoodItem(arg0: string, arg1: string): Promise<DietLogEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.logFoodItem(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logFoodItem(arg0, arg1);
            return result;
        }
    }
    async loginUser(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.loginUser(arg0, arg1);
                return from_candid_variant_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginUser(arg0, arg1);
            return from_candid_variant_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async markKitReceived(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markKitReceived(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markKitReceived(arg0);
            return result;
        }
    }
    async placeOrder(arg0: Array<OrderItem>): Promise<ShoppingOrder> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(arg0);
            return result;
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, arg2);
                return from_candid_variant_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, arg2);
            return from_candid_variant_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendChatMessage(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.sendChatMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendChatMessage(arg0);
            return result;
        }
    }
    async subscribePlan(arg0: PlanType, arg1: string, arg2: string, arg3: string, arg4: string): Promise<Subscription> {
        if (this.processError) {
            try {
                const result = await this.actor.subscribePlan(to_candid_PlanType_n34(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4);
                return from_candid_Subscription_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.subscribePlan(to_candid_PlanType_n34(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4);
            return from_candid_Subscription_n14(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AppointmentStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppointmentStatus): AppointmentStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Appointment_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Appointment): Appointment {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_BookingStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_CallType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CallType): CallType {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_ChatMessage_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChatMessage): ChatMessage {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_ExerciseBooking_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExerciseBooking): ExerciseBooking {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_KitStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KitStatus): KitStatus {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_MessageRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageRole): MessageRole {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_PlanType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlanType): PlanType {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_ProductCategory_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductCategory): ProductCategory {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Subscription_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Subscription): Subscription {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _BookingStatus;
    userId: _UserId;
    bookingDate: _Timestamp;
    sessionId: bigint;
    timeSlot: string;
}): {
    id: bigint;
    status: BookingStatus;
    userId: UserId;
    bookingDate: Timestamp;
    sessionId: bigint;
    timeSlot: string;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n11(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        bookingDate: value.bookingDate,
        sessionId: value.sessionId,
        timeSlot: value.timeSlot
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    purchaseDate: _Timestamp;
    userId: _UserId;
    name: string;
    email: string;
    address: string;
    kitStatus: _KitStatus;
    phone: string;
    orderNumber: _OrderNumber;
    amount: bigint;
    planType: _PlanType;
}): {
    id: bigint;
    purchaseDate: Timestamp;
    userId: UserId;
    name: string;
    email: string;
    address: string;
    kitStatus: KitStatus;
    phone: string;
    orderNumber: OrderNumber;
    amount: bigint;
    planType: PlanType;
} {
    return {
        id: value.id,
        purchaseDate: value.purchaseDate,
        userId: value.userId,
        name: value.name,
        email: value.email,
        address: value.address,
        kitStatus: from_candid_KitStatus_n16(_uploadFile, _downloadFile, value.kitStatus),
        phone: value.phone,
        orderNumber: value.orderNumber,
        amount: value.amount,
        planType: from_candid_PlanType_n18(_uploadFile, _downloadFile, value.planType)
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    content: string;
    userId: _UserId;
    role: _MessageRole;
    timestamp: _Timestamp;
}): {
    id: bigint;
    content: string;
    userId: UserId;
    role: MessageRole;
    timestamp: Timestamp;
} {
    return {
        id: value.id,
        content: value.content,
        userId: value.userId,
        role: from_candid_MessageRole_n25(_uploadFile, _downloadFile, value.role),
        timestamp: value.timestamp
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    description: string;
    imageUrl: [] | [string];
    category: _ProductCategory;
    price: bigint;
}): {
    id: bigint;
    name: string;
    description: string;
    imageUrl?: string;
    category: ProductCategory;
    price: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        imageUrl: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.imageUrl)),
        category: from_candid_ProductCategory_n31(_uploadFile, _downloadFile, value.category),
        price: value.price
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _AppointmentStatus;
    doctorId: bigint;
    userId: _UserId;
    createdAt: _Timestamp;
    slot: string;
    callType: _CallType;
    confirmationNumber: string;
}): {
    id: bigint;
    status: AppointmentStatus;
    doctorId: bigint;
    userId: UserId;
    createdAt: Timestamp;
    slot: string;
    callType: CallType;
    confirmationNumber: string;
} {
    return {
        id: value.id,
        status: from_candid_AppointmentStatus_n4(_uploadFile, _downloadFile, value.status),
        doctorId: value.doctorId,
        userId: value.userId,
        createdAt: value.createdAt,
        slot: value.slot,
        callType: from_candid_CallType_n6(_uploadFile, _downloadFile, value.callType),
        confirmationNumber: value.confirmationNumber
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Booked: null;
} | {
    Cancelled: null;
}): BookingStatus {
    return "Booked" in value ? BookingStatus.Booked : "Cancelled" in value ? BookingStatus.Cancelled : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Received: null;
} | {
    Pending: null;
}): KitStatus {
    return "Received" in value ? KitStatus.Received : "Pending" in value ? KitStatus.Pending : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    OneYear: null;
} | {
    SixMonth: null;
} | {
    ThreeMonth: null;
}): PlanType {
    return "OneYear" in value ? PlanType.OneYear : "SixMonth" in value ? PlanType.SixMonth : "ThreeMonth" in value ? PlanType.ThreeMonth : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    User: null;
} | {
    Assistant: null;
}): MessageRole {
    return "User" in value ? MessageRole.User : "Assistant" in value ? MessageRole.Assistant : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    DiabetesFood: null;
} | {
    Medicine: null;
} | {
    ExerciseEquipment: null;
}): ProductCategory {
    return "DiabetesFood" in value ? ProductCategory.DiabetesFood : "Medicine" in value ? ProductCategory.Medicine : "ExerciseEquipment" in value ? ProductCategory.ExerciseEquipment : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Confirmed: null;
} | {
    Cancelled: null;
}): AppointmentStatus {
    return "Confirmed" in value ? AppointmentStatus.Confirmed : "Cancelled" in value ? AppointmentStatus.Cancelled : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    VideoCall: null;
} | {
    NormalCall: null;
}): CallType {
    return "VideoCall" in value ? CallType.VideoCall : "NormalCall" in value ? CallType.NormalCall : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Appointment>): Array<Appointment> {
    return value.map((x)=>from_candid_Appointment_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Subscription>): Array<Subscription> {
    return value.map((x)=>from_candid_Subscription_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChatMessage>): Array<ChatMessage> {
    return value.map((x)=>from_candid_ChatMessage_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExerciseBooking>): Array<ExerciseBooking> {
    return value.map((x)=>from_candid_ExerciseBooking_n9(_uploadFile, _downloadFile, x));
}
function to_candid_CallType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CallType): _CallType {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_PlanType_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlanType): _PlanType {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CallType): {
    VideoCall: null;
} | {
    NormalCall: null;
} {
    return value == CallType.VideoCall ? {
        VideoCall: null
    } : value == CallType.NormalCall ? {
        NormalCall: null
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlanType): {
    OneYear: null;
} | {
    SixMonth: null;
} | {
    ThreeMonth: null;
} {
    return value == PlanType.OneYear ? {
        OneYear: null
    } : value == PlanType.SixMonth ? {
        SixMonth: null
    } : value == PlanType.ThreeMonth ? {
        ThreeMonth: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
